export enum EnvVariable {
  Port = 'PORT',
  JwtSecret = 'JWT_SECRET',
  JwtExpiration = 'JWT_EXPIRATION',
  GoogleClientId = 'GOOGLE_CLIENT_ID',
  GoogleClientSecret = 'GOOGLE_CLIENT_SECRET',
  GoogleCallback = 'GOOGLE_CALLBACK',
  FacebookClientId = 'FACEBOOK_CLIENT_ID',
  FacebookClientSecret = 'FACEBOOK_CLIENT_SECRET',
  FacebookCallback = 'FACEBOOK_CALLBACK',
  Owner_whatsApp_phone = 'OWNER_WHATSAPP_PHONE',
  MongodbUri = 'MONGODB_URI',
  DataBaseType = 'DB_TYPE',
  DataBaseHost = 'DB_HOST',
  DataBasePort = 'DB_PORT',
  DataBaseUserName = 'DB_USERNAME',
  DataBasePassword = 'DB_PASSWORD',
  DataBaseName = 'DB_NAME',
  IsDataBaseSynchronize = 'DB_SYNCHRONIZE',
}
